### ISSUE TITLE
shape not defined error

### ISSUE THREAD

**Issue by krshrimali** [jiawenzhou0627/IQA-python#1]
Looks like shape has not been declared, in the code. 
Kindly check and correct the code.

Thanks!

**Comment by suke27** [comment]
@krshrimali do you resolve this problem, I found same error

**Comment by krshrimali** [comment]
@suke27 I'll update soon. Trying some experiments, and it should get resolved soon.

**Comment by krshrimali** [comment]
@suke27 - Have opened a pull request and resolved some things about the function, you can check them here or in the pull request : 
https://github.com/krshrimali/image-quality-assessment-python

Will also make some important changes soon.
